version: '3.2'
services:
  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - 12345:8080
    volumes:
      - hehe:/var/jenkins_home

volumes:
  hehe: